name: Build and Deploy to ECS Fargate

on:
  push:
    branches:
      - main
      

jobs:
  deploy:
    name: Build, Push to ECR, and Deploy to ECS Fargate
    runs-on: ubuntu-latest
    environment: naga

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_PROD }}
      ECS_CLUSTER: ${{ secrets.ECS_CLUSTER_PROD }}
      ECS_SERVICE: ${{ secrets.ECS_SERVICE_PROD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t $ECR_REPOSITORY:latest \
            .

      - name: Tag Docker image
        run: |
          docker tag \
            $ECR_REPOSITORY:latest \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest

  
      - name: Wait for ECR image to be fully available
        run: sleep 30

      - name: Force deploy to ECS Fargate
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER_PROD \
            --service $ECS_SERVICE_PROD \
            --force-new-deployment
